### ISSUE TITLE
No permission to google drive

### ISSUE THREAD

**Issue by jingxaolon** [wangzheng422/docker_env#1]
hi,wangzheng!

the installation package issued here:
https://drive.google.com/drive/u/2/folders/18d7qLYrN6qA3QnTFxMXkq9v5jHSiQ2qT

I don’t have permission to access the URL you provided. Is it convenient to provide your contact information and give permission to download?

thanks

**Comment by wangzheng422** [comment]
the google drive is protected by company's policy, you have to build the package by yourself.
