### ISSUE TITLE
ImagePullBackOff

### ISSUE THREAD

**Issue by cgleiyucun** [wangzheng422/docker_env#11]
请问我从git导入代码进行部署，pod提示ImagePullBackOff，Back-off pulling image，
Image Stream Details显示no image found，请问这是缺少什么配置导致的
![image](https://user-images.githubusercontent.com/42564884/210748746-d490f72a-29fe-4b88-9efb-adbf6e50ed92.png)

**Comment by wangzheng422** [comment]
要看你的yaml才知道

**Comment by cgleiyucun** [comment]
遇到了一个新问题，podman处于running状态
但是服务显示不可用
![1672914852101](https://user-images.githubusercontent.com/42564884/210759963-27a9c338-373b-4f01-ae81-84bf2bdba6e5.png)

**Comment by wangzheng422** [comment]
这个一般就是router到pod的链路不通，至于为什么不通，一般有pod里面的服务不正常，service定义不对，router本身就有问题，或者sdn有问题，要逐一分析和排查啦。。。
