### ISSUE TITLE
能否通过Google云盘的访问申请

### ISSUE THREAD

**Issue by rllzyy** [wangzheng422/docker_env#3]
以下是本次使用的虚拟机配置： https://docs.google.com/spreadsheets/d/1dwgh72r4ZfxEIFV82e_qe0T4w3CpENG_HqSejB3IUQs/edit#gid=0

本次实验的简要说明： https://docs.google.com/presentation/d/1_iy_YWnr6YX1tkwhw46ttCMkEoyPcHXvZvGQBDqJMyI/edit
打包好的安装包，在这里下载(internal access only)，目前最新版本是ocp 4.2.13： https://drive.google.com/drive/u/2/folders/1KYTMQnurBYwIz9Qh64_G2gILNiDP6C9e
申请者
rllzyy@gmail.com
谢谢

**Comment by wangzheng422** [comment]
已经放了百度盘链接，参考文档  https://github.com/wangzheng422/docker_env/blob/dev/redhat/ocp4/4.3/4.3.disconnect.operator.md
