### ISSUE TITLE
请问，尝试过利用multus，使用openshift-snd作为主网络，calico作为副网络吗？

### ISSUE THREAD

**Issue by XueCangQiuYe** [wangzheng422/docker_env#4]
我这里已经可以做到使用openshift-snd作为主网络，macvlan作为副网络。并且pod可以固定副网络的ip。但是这个副网络的ip，只能pod间ping通。pod与宿主机间的通信无法使用副网络ping通。

所以，我想使用calico作为副网络尝试一下，想问一下，您有这方面的经验可以分享吗？

**Comment by wangzheng422** [comment]
macvlan访问主机的问题，参考这个文章 https://github.com/wangzheng422/docker_env/blob/master/redhat/ocp4/4.2.macvlan.md ， 如果交换机上能配合vlan的配置，用vlan的方式，走上层路由器转发，也是可以的。

我没做过calico的副网络平台，主网络平面，参考这个文章，https://github.com/wangzheng422/docker_env/blob/master/redhat/ocp4/4.3/4.3.calico.md
