### ISSUE TITLE
我在rhel8 容器中编译报这个错，该怎么解决呢？

### ISSUE THREAD

**Issue by fu7100** [wangzheng422/docker_env#8]
[root@187d368498b4 lkm_example]# make
make -C /lib/modules/4.18.0-193.el8.x86_64/build M=/root/src/lkm_example modules
make[1]: Entering directory '/usr/lib/modules/4.18.0-193.el8.x86_64/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/4.18.0-193.el8.x86_64/build'
make: *** [Makefile:3: all] Error 2

**Comment by wangzheng422** [comment]
我这里在rhel8上测试，正常的。容器里面 kernel-core-$(uname -r) 装了吗？
